<a href="https://colab.research.google.com/github/SushanthikPoreddy/data690_sushanthik/blob/main/individual_project_partB_Draft/individual_project_partB_Draft.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Codes to generate the graphs that are included in the Part A documentation report.

- *Name : Sushanthik Reddy*

In [1]:
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
import plotly.io as pio

In [2]:
pio.templates

Templates configuration
-----------------------
    Default template: 'plotly'
    Available templates:
        ['ggplot2', 'seaborn', 'simple_white', 'plotly',
         'plotly_white', 'plotly_dark', 'presentation', 'xgridoff',
         'ygridoff', 'gridon', 'none']

In [3]:
pio.templates.default = "plotly_dark"

In [4]:
import plotly

print(plotly.__version__)

5.3.1

In [5]:
!pip install plotly --upgrade

Requirement already satisfied: plotly in /usr/local/lib/python3.7/dist-packages (5.3.1)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from plotly) (1.15.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from plotly) (8.0.1)

In [6]:
print(plotly.__version__)

5.3.1

In [7]:
df = pd.read_csv("https://raw.githubusercontent.com/SushanthikPoreddy/data690_sushanthik/main/individual_project_partB_Draft/wdi_data%20(3).csv")
df.head(10)

   Unnamed: 0  Year  ...         Income Group Lending Type
0           0  2015  ...  Lower middle income          IDA
1           1  2016  ...  Lower middle income          IDA
2           2  2017  ...  Lower middle income          IDA
3           3  2018  ...  Lower middle income          IDA
4           4  2019  ...  Lower middle income          IDA
5           5  2020  ...  Lower middle income          IDA
6           6  2015  ...  Upper middle income         IBRD
7           7  2016  ...  Upper middle income         IBRD
8           8  2017  ...  Upper middle income         IBRD
9           9  2018  ...  Upper middle income         IBRD

[10 rows x 9 columns]

## GDP per capita by year in different countries:

In [8]:
df_GDP = df.query('indicator == "NY.GDP.PCAP.PP.CD"')
df_GDP.head(10)

   Unnamed: 0  Year  ...         Income Group Lending Type
0           0  2015  ...  Lower middle income          IDA
1           1  2016  ...  Lower middle income          IDA
2           2  2017  ...  Lower middle income          IDA
3           3  2018  ...  Lower middle income          IDA
4           4  2019  ...  Lower middle income          IDA
5           5  2020  ...  Lower middle income          IDA
6           6  2015  ...  Upper middle income         IBRD
7           7  2016  ...  Upper middle income         IBRD
8           8  2017  ...  Upper middle income         IBRD
9           9  2018  ...  Upper middle income         IBRD

[10 rows x 9 columns]

In [9]:
df_GDP.drop(columns = ["Unnamed: 0"], inplace=True)
df_GDP.head(10)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

   Year         value  ...         Income Group Lending Type
0  2015   3555.505260  ...  Lower middle income          IDA
1  2016   3848.957664  ...  Lower middle income          IDA
2  2017   4160.703325  ...  Lower middle income          IDA
3  2018   4547.479572  ...  Lower middle income          IDA
4  2019   4954.761400  ...  Lower middle income          IDA
5  2020   5082.680750  ...  Lower middle income          IDA
6  2015  12978.768911  ...  Upper middle income         IBRD
7  2016  13572.619989  ...  Upper middle income         IBRD
8  2017  14344.421239  ...  Upper middle income         IBRD
9  2018  15608.967069  ...  Upper middle income         IBRD

[10 rows x 8 columns]

In [10]:
df_pivot1 = df_GDP.pivot(index =['Year','Country Code','Country Name','Region','Income Group','Lending Type'],columns = 'indicator', values ='value').reset_index()
df_pivot1.reset_index().head()

indicator  index  Year  ...    Lending Type NY.GDP.PCAP.PP.CD
0              0  2015  ...             IDA       3555.505260
1              1  2015  ...            IBRD      12978.768911
2              2  2015  ...  Not classified      34903.127478
3              3  2015  ...  Not classified      42567.591797
4              4  2015  ...            IBRD       5464.859178

[5 rows x 8 columns]

In [11]:
fig = px.line(
    df_pivot1, 
    x="Year", 
    y="NY.GDP.PCAP.PP.CD",
    labels={"NY.GDP.PCAP.PP.CD":"GDP per capita, PPP (current international $)"},
    hover_name='Country Name',
    color='Country Name'
    )
fig.show()

## Mortality rate due to unsafe water, unsafe sanitation, and lack of hygiene in different countries:

In [12]:
df_2016 = df.query("Year == 2016")
df_2016.sample(10)

    Unnamed: 0  Year  ...         Income Group    Lending Type
85          85  2016  ...          High income  Not classified
7            7  2016  ...  Upper middle income            IBRD
51          51  2016  ...          High income  Not classified
13          13  2016  ...  Lower middle income            IBRD
48          48  2016  ...  Lower middle income             IDA
50          50  2016  ...  Lower middle income            IBRD
73          73  2016  ...          High income  Not classified
61          61  2016  ...  Upper middle income            IBRD
67          67  2016  ...  Lower middle income            IBRD
55          55  2016  ...  Lower middle income             IDA

[10 rows x 9 columns]

In [13]:
df_2016 = df_2016[df_2016["indicator"].isin(['SH.STA.WASH.P5'])]
df_2016.head()

    Unnamed: 0  Year  ...         Income Group    Lending Type
48          48  2016  ...  Lower middle income             IDA
49          49  2016  ...  Upper middle income            IBRD
50          50  2016  ...  Lower middle income            IBRD
51          51  2016  ...          High income  Not classified
52          52  2016  ...          High income  Not classified

[5 rows x 9 columns]

In [14]:
df_2016.drop(columns = ["Unnamed: 0","Year"], inplace=True)
df_2016.head(10)

    value       indicator  ...         Income Group    Lending Type
48   11.9  SH.STA.WASH.P5  ...  Lower middle income             IDA
49    0.6  SH.STA.WASH.P5  ...  Upper middle income            IBRD
50   18.6  SH.STA.WASH.P5  ...  Lower middle income            IBRD
51    0.2  SH.STA.WASH.P5  ...          High income  Not classified
52    0.2  SH.STA.WASH.P5  ...          High income  Not classified
53    0.2  SH.STA.WASH.P5  ...          High income  Not classified

[6 rows x 7 columns]

In [15]:
df_pivot = df_2016.pivot(index =['Country Code','Country Name','Region','Income Group','Lending Type'],columns = 'indicator', values ='value').reset_index()
df_pivot.reset_index().head()

indicator  index Country Code  ...    Lending Type SH.STA.WASH.P5
0              0          BGD  ...             IDA           11.9
1              1          CHN  ...            IBRD            0.6
2              2          ESP  ...  Not classified            0.2
3              3          GBR  ...  Not classified            0.2
4              4          IND  ...            IBRD           18.6

[5 rows x 7 columns]

In [16]:
fig = px.bar(
    df_pivot,
    x="Country Name",
    y="SH.STA.WASH.P5",
    labels={"SH.STA.WASH.P5":"2016Mortality rate attributed to unsafe water, unsafe sanitation,<br> and lack of hygiene (per 100,000 population)"},
    color="Country Name"
)
fig.update_xaxes(categoryorder="total descending")
fig.show()

## How does mortality rate relate with total population and number of deaths that are caused by the communicable diseases?

In [17]:
df_Deaths = df.query('indicator == "SH.DTH.COMM.ZS"')
df_Deaths.head(10)

    Unnamed: 0  Year  ...         Income Group    Lending Type
36          36  2015  ...  Lower middle income             IDA
37          37  2019  ...  Lower middle income             IDA
38          38  2015  ...  Upper middle income            IBRD
39          39  2019  ...  Upper middle income            IBRD
40          40  2015  ...  Lower middle income            IBRD
41          41  2019  ...  Lower middle income            IBRD
42          42  2015  ...          High income  Not classified
43          43  2019  ...          High income  Not classified
44          44  2015  ...          High income  Not classified
45          45  2019  ...          High income  Not classified

[10 rows x 9 columns]

In [18]:
df_Deaths.drop(columns = ["Unnamed: 0"], inplace=True)
df_Deaths.head(10)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

    Year      value  ...         Income Group    Lending Type
36  2015  28.807663  ...  Lower middle income             IDA
37  2019  22.612837  ...  Lower middle income             IDA
38  2015   4.132797  ...  Upper middle income            IBRD
39  2019   3.549711  ...  Upper middle income            IBRD
40  2015  28.260253  ...  Lower middle income            IBRD
41  2019  24.166184  ...  Lower middle income            IBRD
42  2015   5.324214  ...          High income  Not classified
43  2019   5.610445  ...          High income  Not classified
44  2015   8.066941  ...          High income  Not classified
45  2019   8.156775  ...          High income  Not classified

[10 rows x 8 columns]

In [40]:
df_pivot2 = df_Deaths.pivot(index =['Year','Country Code','Country Name','Region','Income Group','Lending Type'],columns = 'indicator', values ='value').reset_index()
df_pivot2.reset_index().head()

indicator  index  Year  ...    Lending Type SH.DTH.COMM.ZS
0              0  2015  ...             IDA      28.807663
1              1  2015  ...            IBRD       4.132797
2              2  2015  ...  Not classified       5.324214
3              3  2015  ...  Not classified       8.066941
4              4  2015  ...            IBRD      28.260253

[5 rows x 8 columns]

In [41]:
fig = px.line(
    df_pivot2.dropna(),
    x="Year", 
    y="SH.DTH.COMM.ZS",
    color='Country Name',
    hover_name = "Country Name",
    labels={"SH.DTH.COMM.ZS":"Cause of death, by communicable diseases and maternal,<br> prenatal and nutrition conditions (% of total)"}
    )
#fig.update_xaxes(type='category')
fig.show()

### For this chart we see 2015.5, 2016.5 like that stuff between the years if we not use "fig.update_xaxes(type='category')".

### The same above data is used to get the following line graph. But in this case we are including "fig.update_xaxes(type='category')" as part of our code. But in this case we only see 2015 and 2019 because their is no data for the inbetween years in the www.worlddev.xyz source. When I checked the graph in that website and placed cursor on that graph I dont see any data being hovered for the years 2016, 2017, 2018. I only see the data for 2015 and 2019 being hovered when I placed cursor on the graph.
### So, that is the reason I only see the years 2015 and 2019 in my graph when I use "fig.update_xaxes(type='category')"

In [42]:
fig = px.line(
    df_pivot2.dropna(),
    x="Year", 
    y="SH.DTH.COMM.ZS",
    color='Country Name',
    hover_name = "Country Name",
    labels={"SH.DTH.COMM.ZS":"Cause of death, by communicable diseases and maternal,<br> prenatal and nutrition conditions (% of total)"}
    )
fig.update_xaxes(type='category')
fig.show()

In [21]:
df_2015 = df.query("Year == 2015")
df_2015.sample(10)

    Unnamed: 0  Year  ...         Income Group    Lending Type
54          54  2015  ...  Lower middle income             IDA
6            6  2015  ...  Upper middle income            IBRD
40          40  2015  ...  Lower middle income            IBRD
12          12  2015  ...  Lower middle income            IBRD
84          84  2015  ...          High income  Not classified
72          72  2015  ...          High income  Not classified
24          24  2015  ...          High income  Not classified
78          78  2015  ...          High income  Not classified
66          66  2015  ...  Lower middle income            IBRD
0            0  2015  ...  Lower middle income             IDA

[10 rows x 9 columns]

In [22]:
df_2015.drop(columns = ["Unnamed: 0","Year" ],inplace=True)
df_2015.head(10)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

           value          indicator  ...         Income Group    Lending Type
0    3555.505260  NY.GDP.PCAP.PP.CD  ...  Lower middle income             IDA
6   12978.768911  NY.GDP.PCAP.PP.CD  ...  Upper middle income            IBRD
12   5464.859178  NY.GDP.PCAP.PP.CD  ...  Lower middle income            IBRD
18  34903.127478  NY.GDP.PCAP.PP.CD  ...          High income  Not classified
24  42567.591797  NY.GDP.PCAP.PP.CD  ...          High income  Not classified
30  56863.371496  NY.GDP.PCAP.PP.CD  ...          High income  Not classified
36     28.807663     SH.DTH.COMM.ZS  ...  Lower middle income             IDA
38      4.132797     SH.DTH.COMM.ZS  ...  Upper middle income            IBRD
40     28.260253     SH.DTH.COMM.ZS  ...  Lower middle income            IBRD
42      5.324214     SH.DTH.COMM.ZS  ...          High income  Not classified

[10 rows x 7 columns]

In [23]:
df_pivot = df_2015.pivot(index =['Country Code','Country Name','Region','Income Group','Lending Type'],columns = 'indicator', values ='value').reset_index()
df_pivot.reset_index().head()

indicator  index Country Code  ... SH.DTH.COMM.ZS   SP.POP.TOTL
0              0          BGD  ...      28.807663  1.562563e+08
1              1          CHN  ...       4.132797  1.371220e+09
2              2          ESP  ...       5.324214  4.644483e+07
3              3          GBR  ...       8.066941  6.511622e+07
4              4          IND  ...      28.260253  1.310152e+09

[5 rows x 9 columns]

In [24]:
fig = px.pie(df_pivot, values='SP.POP.TOTL', names='Country Name', title='Total Population',hover_name='Country Name')
fig.update_traces(textposition='inside', textinfo='percent+label')
fig.show()